### ISSUE TITLE
Add monitoring for the service

### ISSUE THREAD

**Issue by dns2utf8** [SpaceApi/validator#22]
So we catch it the next time it goes down.

**Comment by dbrgn** [comment]
Not necessary anymore, I added the auto-restart option to the Systemd unit file. Next time it goes down it should be restarted automatically.

**Comment by alexdor** [comment]
@dbrgn validator seems to be down

**Comment by dbrgn** [comment]
@alexdor thanks for letting me know, should be fixed now. restart config wasn't strict enough 😔

**Comment by alexdor** [comment]
That was fast, thanks for restoring it : )

**Comment by dbrgn** [comment]
Great to hear that there are actually people using it 😆

**Comment by alexdor** [comment]
We are writing our new API over at [LambdaSpace](https://github.com/lambdaspace/LambdaSpaceAPIv2), so I'm currently writing tests to validate that our response is compatible with the spec.

Please let us know if we can help with the main project as well : )

**Comment by dbrgn** [comment]
Cool!

> Please let us know if we can help with the main project as well : )

We're still trying to sort things out with the original maintainer. Hoping to make the community around the SpaceAPI more active :)

**Comment by alexdor** [comment]
Hi @dbrgn, sorry for bugging you again but validator seems to be down

**Comment by dbrgn** [comment]
Hm, that is strange. The system service is enabled and restart policy is set to `always`. I'll have to investigate this further.

**Comment by alexdor** [comment]
Would it help if I dockerize the validator? I had great success keeping
services up using Docker’s restart policies

**Comment by dbrgn** [comment]
It's back up, and the problem should be fixed now.

The service is started through systemd. I think I just forgot the `[Install]` section in the service file 😄

**Comment by rnestler** [comment]
@dbrgn  Maybe you could test it? If you just kill the process manually systemd should try to restart it no?

**Comment by dbrgn** [comment]
Yes, that works. The problem was that it wasn't started on boot in the first place, because there was no dependency on it from any boot stage. But now `/etc/systemd/system/multi-user.target.wants/spacedirectory-validator.service` exists (which it didn't before), so everything should be fine 🙂
