### ISSUE TITLE
contact is not validated properly

### ISSUE THREAD

**Issue by Bouni** [SpaceApi/validator#34]
I just realized that `contact`is not validated properly.
If I put this into the validator:
```
...
"contact": {
        "email": "info@dev.dev",
        "issue_mail": "issue@dev.dev",
        "invalid_entry_in_contact": "list@dev.dev"
    },
...
```
I get:
`{"valid": true, "message": null}`

**Comment by dbrgn** [comment]
Hmm, seems that the JSON schema library validates non-strict by default, so unknown entries are ignored.

We'll have to find out if that behavior can be disabled, except for keys starting with `ext_`.

**Comment by gidsi** [comment]
I think we agreed on, that extra fields are not an error, so i will close this for now
