### ISSUE TITLE
cache description doesn't match validation

### ISSUE THREAD

**Issue by Bouni** [SpaceApi/validator#35]
The description of the cache schedule states that:

> This field must match the basic regular expression ^[mhd]\.[0-9]{2}$

Valid values are listed as `m.02 | m.05 | m.10 | m.15 | m.30 | h.01 | h.02 | h.04 | h.08 | h.12 | d.01` and the validator validates only these exact values which is contradictive to the above regex.

I'm not sure if thats a flaw in the schema itself as it has an [enum](https://github.com/SpaceApi/schema/blob/6af8db6d28b70f64742e47a43874285a66c63f8d/13.json#L1069-L1080) that consists of these exact values or if the validator should use the regex instead.

**Comment by dbrgn** [comment]
Good catch!

We removed the caching key in the next version of the schema, so this should become a non-issue :slightly_smiling_face: 

https://github.com/SpaceApi/schema/pull/46
