### ISSUE TITLE
issue_report_channels is required

### ISSUE THREAD

**Issue by bullestock** [SpaceApi/validator#66]
When I validate my new endpoint using

`curl -X POST -H "Content-Type: application/json"  https://validator.spaceapi.io/v2/validateURL -d'{"url": "https://acsgateway.hal9k.dk/spaceapi"}'`

I get the error

`"schemaErrors": [
    {
      "field": "(root)",
      "message": "issue_report_channels is required"
    }
  ]`

I don't see this field in the schema, so what does the error mean?

**Comment by dbrgn** [comment]
This field was removed in v14, but it was still required in v0.13.

Your endpoint claims compatibility with both v0.13 and v14, thus it needs to include that field.

The website only shows docs for v14, but you can find the description here: https://github.com/SpaceApi/schema/blob/master/13.json#L263-L276

**Comment by bullestock** [comment]
@dbrgn  Thanks!

**Comment by bullestock** [comment]
Closing this.
