### ISSUE TITLE
Validator parses schema every time a validation is requested

### ISSUE THREAD

**Issue by rnestler** [SpaceApi/validator#8]
Currently every time `validate_spaceapi_json` is called, the JSON schema file is parsed. We could solve this by either using https://github.com/rust-lang-nursery/lazy-static.rs or by using a struct which holds the parsed schemata.

**Comment by dbrgn** [comment]
Yeah, we could create a struct `Validator` which caches the parsed schemata. The latest schema (v13) could also be initialized in the constructor.

**Comment by dns2utf8** [comment]
Maybe the compiler is able to infer, that the result will always be the same and just precalculate it.
